name: 🚀 Deploy and Publish website on "Push"
on:
  push:
    branches:
      - 'main'
jobs:

  web-deploy:
    name: 🎉 Deploy and Publish
    runs-on: ubuntu-latest
    
    steps:
    
    - name: 🚚 Checkout code from repo to "Actions" work folder
      uses: actions/checkout@v2    
      
    - name: 🚚 Sync latest code to "Apache" webserver
      uses: easingthemes/ssh-deploy@main
      with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-avzr --delete"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            EXCLUDE: ".git , .github"
            SCRIPT_AFTER: |
              systemctl reload apache2
              systemctl status apache2
